# Generated by Django 4.2.7 on 2023-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_image', models.ImageField(upload_to='pre_images/')),
                ('post_image', models.ImageField(upload_to='post_images/')),
            ],
        ),
    ]
