# Generated by Django 4.2.7 on 2023-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepair',
            name='output_damage',
            field=models.ImageField(blank=True, upload_to='output_images/'),
        ),
        migrations.AddField(
            model_name='imagepair',
            name='output_segment',
            field=models.ImageField(blank=True, upload_to='output_images/'),
        ),
    ]
