# Generated by Django 4.2.7 on 2023-12-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagepair_title_alter_imagepair_output_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepair',
            name='damage_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
